### ISSUE TITLE
Totally skipping some style rules when bundling.

### ISSUE THREAD

**Issue by SirCameron** [tr1s/tris-shopify-webpack-boilerplate#12]
Firstly, thanks for this boilerplate.

It's been a pleasure to use so far... except for one thing: it totally skips some style rules when bundling.
I'm unable to give you access to the repo this is ocuring on, but I'm creating the issue to see if other developers are hitting this issue and can provide more info.

**Comment by tr1s** [comment]
No problem!

It's probably purgecss which is causing an undesirable effect of purging some CSS styles you might actually want? The idea is that it get's rid of CSS that you're not using, to lighten the bundle.

Try deleting these lines in the `postcss.config.js` 

```js
    purgecss({
      content: ['./**/*.html', './**/*.liquid'],
      keyframes: true
    })
```

**Comment by SirCameron** [comment]
Thanks @tr1s 
How does it determine if a style is used or not? The styles are definitely used, which is why this is frustrating.
For me, understanding how it knows if a style is used or not would mean I can work with it instead of disabling it.

**Comment by tr1s** [comment]
Yeah sometimes it can be tricky, although I can't specifically remember why... It's been a while.

I'd say read through the [purgecss options](https://purgecss.com/configuration.html#options) to get a better understand how it works.

Figure out specifically what styles are being undesirably purged. Are they coming from js, or from a third-party library? from html or liquid? This will help you determine where to set some custom options that may fix your problem.

**Comment by SirCameron** [comment]
thanks for your help and quick responses @tr1s .
I ended up just removing purgecss as you suggested :)

**Comment by tr1s** [comment]
Fair enough, no problem!
